### ISSUE TITLE
missing a subset runs from a single SRA project

### ISSUE THREAD

**Issue by skinnider** [markziemann/dee2#52]
Hi there,
I really enjoyed your paper on the DEE2 resource in GigaScience and I’m interested in using these precomputed kallisto TPM matrices from a number of different studies as part of one project.
I’m trying to set up a pipeline to download and analyze the files and debugging it with one example dataset, GSE106289. However, it seems that only 27 of the 40 runs from this study are present in DEE2. I checked the QC file and didn't see any indication the other 13 runs failed QC. They also don't seem to be under embargo. I see that there are a large number of runs queued to be processed but the rest of the runs from this study seem to have been processed in Nov-Dec 2018.
I was wondering if you knew why only 27/40 runs from this example study are on DEE2, or whether the remaining runs are queued? An example of a missing run is SRR6231094. I was hoping to understand this better to get a sense of whether this dataset is an anomaly, or whether there might be missing runs from a larger proportion of SRA datasets.
Thanks very much for your help and for this great resource.
Mike

**Comment by markziemann** [comment]
Hi Mike,
Thanks for the message. For GSE106289 I see that 10 runs are yet to be processed. I have just queued them and they will be completed in a few hours. After that I will update the human database and let you know when they are ready (24-48 hrs). It is true that there are some projects with missing datasets, we are working hard to fill in these in.
Mark

**Comment by skinnider** [comment]
Thanks for the quick reply - glad to hear these runs and many others are in the queue.
