### ISSUE TITLE
Replacement to SRAdbV2

### ISSUE THREAD

**Issue by markziemann** [markziemann/dee2#54]
SRAdbV2 has been down for a while now. Not even a static version is available. Luckily I have backups of the necessary metadata.

Over the next month or so I will be investigating options for a replacement, such as https://github.com/seandavi/OmicIDXR/

**Comment by Malili2018** [comment]
Dear markziemann, I'm using your package for data analysis now. I found that the SRAdbV2 package has updated their api website a few days ago. Can you update the code in backend to adjust their current api? Thanks a lot.

**Comment by markziemann** [comment]
Thanks for the message. I have copied seandavi's comment below.

"Sorry, all. We did some substantial updates and changes.
https://github.com/omicidx/omicidx
http://api.omicidx.cancerdatasci.org/redoc"

It will take me some time to make this change. The specific points which are concerning are the change in data format and possibly the fields as compared to the previous R package.

I am wary of spending a lot of time on omicdx as it may also not be maintained for a very long time and go down at some stage. I would rather plug in directly to NCBI.

**Comment by markziemann** [comment]
I am actively working on this issue and will implement a solution by obtaining SRA metadata manually from NCBI, a push is expected in the next 3-4 days

**Comment by markziemann** [comment]
This has been addressed in the past few commits. Most species have included new metadata but mouse and human will be updated in the next week.

**Comment by markziemann** [comment]
@Malili2018 Metadata has been directly downloaded from NCBI and I've updated all species. I will close this issue and feel free to reopen if you need.
