### ISSUE TITLE
SampleName and GSE_accession are identical in hsapiens_metadata.tsv

### ISSUE THREAD

**Issue by rcastelo** [markziemann/dee2#69]
hi,

thank you very much for putting together this fantastic resource, i'd like to use it to check if a study in GEO in which i'm interested in, has some QC problems upfront. i want to do it directly through the metadata but the values in the `GSE_accession` column are not GSE accessions, as illustrated by this R code:

```
download.file("http://dee2.io/metadata/hsapiens_metadata.tsv",
              "dee2_hsapiens_metadata.tsv", method="curl")
dee2 <- read.csv("dee2_hsapiens_metadata.tsv", sep="\t", stringsAsFactors=FALSE)
head(dee2$SampleName)
[1] "SAMD00013986" "SAMD00013986" "SAMD00013986" "SAMD00013986" "SAMD00013986"
[6] "SAMD00002711"
head(dee2$GSE_accession)
[1] "SAMD00013986" "SAMD00013986" "SAMD00013986" "SAMD00013986" "SAMD00013986"
[6] "SAMD00002711"
identical(dee2$SampleName, dee2$GSE_accession)
[1] TRUE
```

would it be possible to fix this column?

thanks!

**Comment by markziemann** [comment]
Hello @rcastelo,
Could you try using the dedicated R package?
```
devtools::install_github("markziemann/dee2/getDEE2")
library("getDEE2")
mdat <- getDee2Metadata("hsapiens")
head(mdat)
```
Then its possible to get the datasets like this:
```
mydat <- getDEE2("hsapiens", c("DRR000003","DRR000004") )
str(mydat)
```

**Comment by rcastelo** [comment]
This doesn't work for me because i've selected datasets based on NCBI metadata and have for them GSEXXXX identifiers and therefore i don't know their DRRXXXXXX identifiers. the `getDEE2` package doesn't sort out the issue because it's downloading the same metadata that apparently lacks GSEXXXX identifiers:

```
library("getDEE2")
mdat <- getDee2Metadata("hsapiens")
head(mdat, 3)
  SRR_accession    QC_summary SRX_accession SRS_accession SRP_accession
1     DRR000003 FAIL(4,5,6,7)     DRX000003     DRS000003     DRP000003
2     DRR000004 FAIL(4,5,6,7)     DRX000003     DRS000003     DRP000003
3     DRR000005 FAIL(4,5,6,7)     DRX000003     DRS000003     DRP000003
  GSE_accession Sample_name             Library_name
1  SAMD00013986             DLD1_normoxia_nucleosome
2  SAMD00013986             DLD1_normoxia_nucleosome
3  SAMD00013986             DLD1_normoxia_nucleosome
grep("GSE", mdat$GSE_accession)
[1] 115547
 mdat$GSE_accession[115547]
[1] 3T-seq_GSE-1
281381 Levels:   293T DUSP11 KO, ribo(-), frag ... ZYN
```
so, obviously the column `GSE_accession` does not have GSE accessions. would it be possible that the column `GSE_accession` has GSE accessions?

**Comment by markziemann** [comment]
I see what you mean. Thanks for identifying this bug. I have tracked down the source of the problem and it will take some time (2 days) for the updated metadata to appear on the DEE2 website. For the time being, you could find the SRP number from[ NCBI GEO](http://www.ncbi.nlm.nih.gov/geo/) and use that to search the DEE2 metadata for your study.

**Comment by rcastelo** [comment]
Excellent, thank you!!

**Comment by markziemann** [comment]
Hi @rcastelo I hope you were able to solve your problem. I'm going to close the issue now, but if you have a similar problem, feel free to open it again.
