### ISSUE TITLE
query to http://dee2.io/metadata/hsapiens_metadata.tsv.cut responds 404

### ISSUE THREAD

**Issue by uilnauyis** [markziemann/dee2#70]
Thank you for your effort in developing and maintaining this tool!

I received a 404 response for requesting http://dee2.io/metadata/hsapiens_metadata.tsv.cut when I tried to obtain DEE2 data for 'hsapiens'. This issue broke the functions 'getDee2Metadata' and 'getDEE2' for getting 'hsapiens' data.

For replicating the issue, try the following code:
`> mdat<-getDee2Metadata("hsapiens")`
`trying URL 'http://dee2.io/metadata/hsapiens_metadata.tsv.cut'`
`Error in download.file(metadataURL, destfile = metadataname, mode = "wb",  : 
  cannot open URL 'http://dee2.io/metadata/hsapiens_metadata.tsv.cut'`
`In addition: Warning message:`
`In download.file(metadataURL, destfile = metadataname, mode = "wb",  :
  cannot open URL 'http://dee2.io/metadata/hsapiens_metadata.tsv.cut': HTTP status was '404 Not Found'`

Or directly make request to http://dee2.io/metadata/hsapiens_metadata.tsv.cut

**Comment by markziemann** [comment]
Hi @uilnauyis, thanks for raising this issue. It looks like a softlink to the metadata was broken for some reason on the webserver. Seems like the other species are OK. I have confirmed that  http://dee2.io/metadata/hsapiens_metadata.tsv.cut is working now.

**Comment by uilnauyis** [comment]
Thanks for fixing the issue. I could confirm the issue has disappeared.
