### ISSUE TITLE
GeneCountMatrix.tsv and TxCountMatrix.tsv are empty downloaded from DEE2

### ISSUE THREAD

**Issue by uilnauyis** [markziemann/dee2#71]
- Issue: When I downloaded the counts data for some H. sapiens samples, I noticed GeneCountMatrix.tsv and TxCountMatrix.tsv are empty, despite the SRA run accessions could be found. The issue exists in both downloading via the web interface and via the R interface. I tried to download the samples one by one, noticing that some of the samples returned empty counts while others returned with count data.

- reproducing the issue: 
The following samples could all by found on DEE2, but when downloading, no matter one by one or all together, the count files returned are empty. Also, if downloading any of these sample together with other samples, the count file will also be empty:
ERR1474907,ERR2105154,ERR2105155,ERR2105156,ERR2105157,ERR2105158,ERR2105159,ERR2105160,ERR2105161,ERR2105162,ERR2105163,ERR2105164,ERR2105165,ERR2105166,ERR2105167,ERR2105168,ERR2105169,ERR2105170,ERR2105171,ERR2105172,ERR2105173,ERR2105174,ERR2105175,ERR2105176,ERR2105177,ERR2105178,ERR2105179,ERR2105180,ERR2105181,ERR2105182,ERR2105183,ERR2105184,ERR2105185,ERR2105186,ERR2105187,ERR2105188,ERR2105189,ERR2105190,ERR2105191,ERR2105192,ERR2105193,ERR2105194,ERR2105195,ERR2105196,ERR2105197,ERR2105198,ERR2105199,ERR2105200,ERR2105201,ERR2105202,ERR2105203,ERR2105204,ERR2105205,ERR2105206,ERR2105207,ERR2105208,ERR2105209,ERR2105210,ERR2105211,ERR2105212,ERR2105213,ERR2105214,ERR2105215,ERR2105216,ERR2105217,ERR2105218,ERR2105219,ERR2105220,ERR2105221,ERR2105222,ERR2105223,ERR2105224,ERR2105226,ERR2105227,ERR2105228,ERR2105229,ERR2105230,ERR2105231,ERR2105232,ERR2105233,ERR2105234,ERR2105235,ERR2105236,ERR2105237,ERR2105238,ERR2105239,ERR2105240,ERR2105241,ERR2105242,ERR2105243,ERR2105244,ERR2105245,ERR2105246,ERR2105247,ERR2105248,ERR2105249,ERR2105250,ERR2105251,ERR2105252,ERR2105253,ERR2105254,ERR2105255,ERR2105256,ERR2105257,ERR2105258,ERR2105260,ERR2105267,ERR2105268,ERR2105269,ERR2105270,ERR2598051,ERR2598056,ERR2598069,ERR2598071,ERR2598080,ERR2598089,ERR2598094,ERR2598102,ERR2598104,ERR2598109,ERR2598110,ERR2598111,ERR2598120,ERR2598121,ERR2598125,ERR2598126,ERR2598127,ERR2598137,ERR2598164,ERR2598165,ERR2598166,ERR2598169,ERR2598170,ERR2598171,ERR2598180,ERR2598181,ERR2598184,ERR2598185,ERR2598195,ERR2598196,ERR2598197,ERR2598198,ERR2598206,ERR2598207,ERR2598208,ERR2598212,ERR2598213,ERR2598214,ERR2598226,ERR2598229,ERR2598235,ERR2598236,ERR2598237,ERR2598238,ERR2598251,ERR2598256,ERR2598257

Thank you!

**Comment by markziemann** [comment]
Thanks for raising this issue - I looked on the server and it appears to be a permission problem. It looks fixed now and I will implement a long term solution at some point. 
Do these datasets download for you properly now?

**Comment by uilnauyis** [comment]
@markziemann Awsome, it works now! Thank you for fixing the issue.
