### ISSUE TITLE
'getDEE2' function could failed to return DEE2 data if .tsv files contain '#' character

### ISSUE THREAD

**Issue by uilnauyis** [markziemann/dee2#77]
For example, the sample_name of sample 'SRR6025297' is '57220_H9_hESC_CSDE1_shRNA_#2_replicate_#3'. If this sample is requested, 'getDEE2' function fails to return the data object, because 'read.table' function treats character '#' as the special character for comments and thus failed to read the 'MetadataFull.tsv' file.

I suggest to add 'comment.char = ''  ' as an argument for all 'read.table' in dee2/getDEE2/R/getDEE2.R to avoid this problem. I could create a pull request for fixing this issue if you'd like to.

**Comment by markziemann** [comment]
Many thanks for reporting this bug. I will have a fix soon.

**Comment by markziemann** [comment]
Hello @uilnauyis  could you try reinstalling and see if it works?
Thanks

**Comment by uilnauyis** [comment]
Awesome! I could confirm the bug has been fixed now. Thanks!
